# Workflow Name: Napravi raspored
# This GitHub Actions workflow triggers on every push to the `main` branch. 
# It runs a Python script to convert bus schedule JSON files into markdown files 
# and commits the generated markdown files back to the repository.
# Finally, it updates the public GitHub Page: rodik.github.io/autobus-sibenik

name: Napravi novi raspored

on:
  # Trigger the workflow on push events to the `main` branch
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  napravi_raspored:
    # Summary:
        # The job will regenrate the bus timetable markdown

    # Specify the operating system/environment for the job
    runs-on: ubuntu-latest
    outputs:
      new_commit_sha: ${{ steps.commit_changes.outputs.commit_sha }}

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      # Use the official GitHub Action to check out the code in the repository
      uses: actions/checkout@v3
      # This step allows subsequent steps to access files in the repository, 
      # including the Python script and JSON files.

    # Step 2: Set up Python environment
    - name: Set up Python
      # Use the official GitHub Action to set up a Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specify the version of Python to use
      # This step ensures the runner has the specified Python version installed.

    # Step 3: Install Python dependencies
    - name: Install dependencies
      # Upgrade pip, and install any dependencies required by the script.
      # If you add dependencies in the future, list them here.
      run: |
        python -m pip install --upgrade pip
      # Currently, no additional packages are installed. If you need packages like `pandas`,
      # add `pip install <package_name>` in this section.

    # Install pandoc
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    # Step 4: Run the conversion script
    - name: Run conversion script
      run: |
        python obrada.py
      # This step runs the Python script (`obrada.py`) which:
      # - Processes all JSON files in a specific directory.
      # - Converts each JSON file to a markdown file with the correct timetable format.
      # - Saves the generated markdown files in a designated output folder (e.g., `timetables`).

    # Step 5: Create index.md for GitHub Pages
    - name: Prepare markdown file for GitHub Pages
      run: |
        # Convert md to html
        pandoc timetables/Combined_Timetable.md -o timetables/index.html

        # Ensure the docs directory exists
        mkdir -p docs
        
        # Move and timetables/index.html to docs folder
        mv timetables/index.html docs/index.html

            
    # Step 6: Commit and push generated index.md file to the repository
    - name: Commit and push generated timetables
      id: commit_changes
      run: |
        # Configure Git with a default user name and email for the commit
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        # Stage the changes
        git add docs/index.html

        # Get build information
        RUN_ID="${GITHUB_RUN_NUMBER}"       # auto-incrementing number unique to each workflow run within the repository
        CURRENT_DATE=$(date +"%Y-%m-%d")    # Current date in yyyy-mm-dd format
        
        # Create a commit message with run ID and date
        git commit -m "raspored verzija - ${RUN_ID}, datum ${CURRENT_DATE}"
        
        # Push the changes back to the `main` branch
        git push
        
        # Capture the new commit SHA
        echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
      env:
        # Use the GitHub-provided token to authenticate the push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This step stages, commits, and pushes the updated markdown files back to the repository.
      # The `GITHUB_TOKEN` provided by GitHub allows the action to authenticate without 
      # requiring additional setup.


  deploy:
    needs: napravi_raspored
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ needs.napravi_raspored.outputs.new_commit_sha }}  # Check out the specific SHA

        - name: Setup Pages
          uses: actions/configure-pages@v5

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: 'docs/'
            
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4